export const ActionType = {
    
    GET_STUDENTS: 'GET_STUDENTS',
    DELETE_STUDENTS:'DELETE_STUDENTS',
    ADD_STUDENTS:'ADD_STUDENTS',
    UPDATE_STUDENTS:'UPDATE_STUDENTS',
    GET_SINGLE_STUDENT:'GET_SINGLE_STUDENT'
}